### ISSUE TITLE
为何构建的页面标签带出来了

### ISSUE THREAD

**Issue by dale426** [ulivz/vuepress-plugin-yuque#15]
![image](https://user-images.githubusercontent.com/23730859/61792255-e853d100-ae4e-11e9-8fc7-fb60bfd0412a.png)

**Comment by dale426** [comment]
版本号 ： 
```shell
vuePress/1.0.2 
darwin-x64 
node-v10.6.0
```

**Comment by LiangGame** [comment]
@dale426 我遇到了同样的问题，你解决了吗?是怎么解决的

**Comment by ulivz** [comment]
Did you enable "html"?

ref: https://vuepress-plugin-yuque.ulivz.com/config.html#html

**Comment by dale426** [comment]
> Did you enable "html"?
> 
> ref: https://vuepress-plugin-yuque.ulivz.com/config.html#html

I'm without used any html tag when i write on the yuque, but it's not analysis， I‘m try to deploy your  demo document, it's like to myself;

![image](https://user-images.githubusercontent.com/23730859/62019150-27d44180-b1f0-11e9-87d1-7921a6593768.png)

it's disable "html".

**Comment by ulivz** [comment]
@dale426 but yuque gave VuePress only the markups instead of markdowns. so you need to enable it.
