### ISSUE TITLE
Can't get data from my private document

### ISSUE THREAD

**Issue by JerichoDing** [ulivz/vuepress-plugin-yuque#2]
According to the document configuration, configure the token, but can not get the document content.

![image](https://user-images.githubusercontent.com/24643872/52551495-b9edb680-2e17-11e9-9418-61d4e998662b.png)

**Comment by ulivz** [comment]
Thanks for the report, fixed at a59c420, actually it's a regression bug of https://github.com/ulivz/vuepress-plugin-yuque/commit/93e0c060e9aaa07bf1bd9a084b2e6a26023be779
