### ISSUE TITLE
配置vuepress-plugin-yuque出错

### ISSUE THREAD

**Issue by imAkaka** [ulivz/vuepress-plugin-yuque#37]
按照快速上手教程试用vuepress插件（https://vuepress-plugin-yuque.ulivz.com/getting-started.html），会报错，截图如下
![image](https://user-images.githubusercontent.com/2075570/75766843-bc051900-5d7c-11ea-8392-a81f0a56f293.png)

**Comment by aidenhe1995** [comment]
老兄，我发现我也是碰到一样的问题，无论是使用官方的repoUrl还是自己的Access Token都是一样报这个错误，多次尝试都是这样

**Comment by imAkaka** [comment]
> 老兄，我发现我也是碰到一样的问题，无论是使用官方的repoUrl还是自己的Access Token都是一样报这个错误，多次尝试都是这样

在yuque的官方论坛发了帖子，他们说这个不是官方维护不更新，算了。

**Comment by aidenhe1995** [comment]
唉，既然不更新那就算了。语雀以后收费不能自定义的话就绝缘吧
