### ISSUE TITLE
自动生成的文章未渲染，全部是html代码

### ISSUE THREAD

**Issue by ldcmd** [ulivz/vuepress-plugin-yuque#39]
![image](https://user-images.githubusercontent.com/25797957/77623518-2e7fa800-6f7b-11ea-8acd-1dd95b99d251.png)

**Comment by qixiaobo** [comment]
需要开启html

**Comment by Mnting** [comment]
> 需要开启html

不好意思，每明白，请问如何开启html？

**Comment by ulivz** [comment]
https://vuepress-plugin-yuque.ulivz.com/config.html#html
