### ISSUE TITLE
你好，为什么npm run dev后，生成的页面html标签没有被渲染？

### ISSUE THREAD

**Issue by zzw118** [ulivz/vuepress-plugin-yuque#6]
你好，为什么npm run dev后，生成的页面html标签没有被渲染？
![_20190227183432](https://user-images.githubusercontent.com/9132607/53484372-abadc480-3abe-11e9-8d18-a0f41e9812e2.png)

**Comment by ulivz** [comment]
See: https://vuepress-plugin-yuque.ulivz.com/config.html#html

**Comment by zzw118** [comment]
ok，谢谢！
