### ISSUE TITLE
缓存

### ISSUE THREAD

**Issue by KyleThanas** [ulivz/vuepress-plugin-yuque#7]
我成功建立项目，部署在github.io上面了

但是我在语雀发的新的文章，修改目录等操作后，使用yarn dev启动服务，还是第一次启动时候的目录

**Comment by ulivz** [comment]
麻烦好好看文档。https://vuepress-plugin-yuque.ulivz.com/cache.html

**Comment by KyleThanas** [comment]
我好好的看过文档了，但是没有理解   SKIP_CACHE    应该如何设置
这是我目前的知识库
![image](https://user-images.githubusercontent.com/19608395/54267084-943d0400-45b3-11e9-8c02-6ff1bbc59d09.png)
无论是build还是dev都是下面的图
![image](https://user-images.githubusercontent.com/19608395/54267128-a9199780-45b3-11e9-9fb5-0530c648c178.png)

**Comment by zzw118** [comment]
@KyleThanas 请问你解决了吗？我也没看明白，我配置了环境变量，也不行

**Comment by jeffwcx** [comment]
不用配啊，直接在命令前加SKIP_CACHE=1
