### ISSUE TITLE
执行build命令打包后，html页面中的引用路径不对

### ISSUE THREAD

**Issue by zzw118** [ulivz/vuepress-plugin-yuque#9]
页面会报找不到文件，去掉前面的‘/’才可以，请问是什么问题呢？

![微信截图_20190423180806](https://user-images.githubusercontent.com/9132607/56573167-137e1880-65f3-11e9-9424-f4574bf3d9ef.png)

**Comment by ulivz** [comment]
什么叫页面找不到文件？请提供一个 repro repo，谢谢。

**Comment by zzw118** [comment]
就是生成的dist目录，里面的index.html页面，在引用assets目录的css或js文件时，路径并不需要加“/”，但是生成的时候却加上了，所以导致文件找不到
![image](https://user-images.githubusercontent.com/9132607/57186938-24dff280-6f1a-11e9-8ae2-fec757726e12.png)

**Comment by ulivz** [comment]
VuePress 默认的 publicPath 是 '/'，你可以用 chainWebpack 设置 publicPath 为 `''`... 另外，推荐用 http-server 或者 [vuepress-plugin-serve](https://github.com/Shigma/vuepress-plugin-serve) 来 preview。

**Comment by zzw118** [comment]
你好，谢谢你的耐心解答，我用http-server可以实现本地的预览了，那如果我想部署到自己的服务器上，该如何做呢，直接拷贝dist目录，也会有之前的问题。
